variable "compartment_id" {}
variable "log_group_display_name" {}
variable "log_display_name" {}
variable "log_type" {}
variable "ua_configuration_description" {}
variable "ua_configuration_display_name" {}
variable "ua_configuration_type" {}
variable "ua_source_type" {}
variable "ua_parser_type" {}
variable "dynamic_group_name" {}
