variable "tenancy_ocid" {}
variable "tenancy_name" {}
variable "compartment_id" {}
variable "ad_number" {}
variable "instance_shape" {}
variable "subnet_id" {}
variable "instance_display_name" {}
variable "os_image_name" {}
variable "tag_namespace_name" {}
variable "tag_namespace_description" {}
variable "tag_name" {}
variable "tag_description" {}
variable "vm_dynamic_group_name" {}
variable "vm_dynamic_group_description" {}
variable "compartment_name" {}
