variable "tenancy_ocid" {}
variable "compartment_id" {}
variable "sch_hub_name" {}
variable "sch_source_kind" {}
variable "sch_target_kind" {}
variable "sch_target_bucket" {}
variable "sch_target_object_name_prefix" {}
variable "sch_description" {}
variable "compartment_name" {}
variable "logs_tenancy" {}
variable "logs_tenancy_id" {}
variable "all_logs_info" {}
