variable "compartment_id" {}
variable "sc_hub_name" {}
variable "sc_source_kind" {}
variable "sc_source_mon_sources_ns_details_kind" {}
variable "sc_source_mon_sources_ns_details_nsps_metrics_kind" {}
variable "sc_source_mon_sources_ns_details_nsps_ns_1" {}
variable "sc_source_mon_sources_ns_details_nsps_ns_2" {}
variable "sc_target_kind" {}
variable "sc_target_bucket" {}
variable "sc_target_object_name_prefix" {}
variable "sc_description" {}
